-- Initial schema for MultiTenantEcommerce
CREATE TABLE Tenants (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    Identifier NVARCHAR(128) NOT NULL UNIQUE,
    Name NVARCHAR(256) NOT NULL,
    IsActive BIT NOT NULL DEFAULT 1,
    TenantId UNIQUEIDENTIFIER NOT NULL,
    CreatedAt DATETIME2 NOT NULL,
    UpdatedAt DATETIME2 NULL
);

ALTER TABLE Tenants ADD DefaultMetaTitle NVARCHAR(256) NULL;
ALTER TABLE Tenants ADD DefaultMetaDescription NVARCHAR(512) NULL;
ALTER TABLE Tenants ADD DefaultMetaKeywords NVARCHAR(512) NULL;
ALTER TABLE Tenants ADD DefaultOgImageUrl NVARCHAR(512) NULL;

CREATE TABLE AnalyticsEvents (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    TenantId UNIQUEIDENTIFIER NOT NULL,
    EventType NVARCHAR(64) NOT NULL,
    OccurredAt DATETIME2 NOT NULL,
    Amount DECIMAL(18,2) NULL,
    RelatedEntityId UNIQUEIDENTIFIER NULL,
    Metadata NVARCHAR(2048) NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2 NULL
);

CREATE INDEX IX_AnalyticsEvents_TenantId_OccurredAt ON AnalyticsEvents (TenantId, OccurredAt);
CREATE INDEX IX_AnalyticsEvents_TenantId_EventType ON AnalyticsEvents (TenantId, EventType, OccurredAt);

CREATE TABLE DailyAnalyticsSummaries (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    TenantId UNIQUEIDENTIFIER NOT NULL,
    [Date] DATE NOT NULL,
    VisitCount INT NOT NULL DEFAULT 0,
    OrderCount INT NOT NULL DEFAULT 0,
    SalesAmount DECIMAL(18,2) NOT NULL DEFAULT 0,
    ConversionRate DECIMAL(18,4) NOT NULL DEFAULT 0,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2 NULL
);

CREATE UNIQUE INDEX IX_DailyAnalyticsSummaries_TenantId_Date
    ON DailyAnalyticsSummaries (TenantId, [Date]);

CREATE TABLE Roles (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    Name NVARCHAR(256) NOT NULL,
    NormalizedName NVARCHAR(256) NOT NULL,
    TenantId UNIQUEIDENTIFIER NOT NULL,
    CreatedAt DATETIME2 NOT NULL,
    UpdatedAt DATETIME2 NULL,
    CONSTRAINT UK_Roles_NormalizedName_Tenant UNIQUE (NormalizedName, TenantId)
);

CREATE TABLE Users (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    UserName NVARCHAR(256) NOT NULL,
    NormalizedUserName NVARCHAR(256) NOT NULL,
    Email NVARCHAR(256) NOT NULL,
    NormalizedEmail NVARCHAR(256) NOT NULL,
    EmailConfirmed BIT NOT NULL DEFAULT 0,
    PasswordHash NVARCHAR(MAX) NOT NULL,
    IsActive BIT NOT NULL DEFAULT 1,
    TenantId UNIQUEIDENTIFIER NOT NULL,
    CreatedAt DATETIME2 NOT NULL,
    UpdatedAt DATETIME2 NULL,
    CONSTRAINT UK_Users_NormalizedUserName_Tenant UNIQUE (NormalizedUserName, TenantId)
);

CREATE TABLE UserRoles (
    UserId UNIQUEIDENTIFIER NOT NULL,
    RoleId UNIQUEIDENTIFIER NOT NULL,
    TenantId UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT PK_UserRoles PRIMARY KEY (UserId, RoleId, TenantId),
    CONSTRAINT FK_UserRoles_Users FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE,
    CONSTRAINT FK_UserRoles_Roles FOREIGN KEY (RoleId) REFERENCES Roles(Id) ON DELETE CASCADE
);

CREATE TABLE RefreshTokens (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    UserId UNIQUEIDENTIFIER NOT NULL,
    Token NVARCHAR(MAX) NOT NULL,
    ExpiresAt DATETIME2 NOT NULL,
    CreatedAt DATETIME2 NOT NULL,
    RevokedAt DATETIME2 NULL,
    TenantId UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT FK_RefreshTokens_Users FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE
);

CREATE INDEX IX_RefreshTokens_UserId ON RefreshTokens(UserId);
